name: Docker Image CI

on:
  push:
    branches:
      - 'test-gh-action'
    paths:
      - 'agora/main_ui/src'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./agora/main_ui/src --file ./agora/main_ui/src/Dockerfile --tag main-ui:$(date +%s)
